[package]
name = "near-lake-primitives"
version = "0.0.0" # managed by cargo-workspaces
edition = "2021"

[dependencies]
anyhow = "1.0.51"
near-crypto = "0.16.0"
near-primitives-core = "0.16.0"
near-indexer-primitives = ">=0.16.0,<0.17.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.75"
