[package]
name = "near-lake-primitives"
version.workspace = true
edition = "2021"

[dependencies]
anyhow = "1.0.51"
near-crypto = "0.17.0"
near-primitives-core = "0.17.0"
near-primitives = "0.17.0"
near-indexer-primitives = "0.17.0"
paste = "1.0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.75"
thiserror = "1.0.38"
