[package]
name = "lake-context-derive"
description = "Derive macro for LakeContext"
edition = "2021"
version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
