[package]
name = "lake-parent-transaction-cache"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = "0.43.0"
derive_builder = "0.12.0"

near-lake-framework = { path = "../lake-framework" }

[dev-dependencies]
anyhow = "1.0.44"