name: Rust

on:
  push:
    branches:
      - main
      - 0.7.x # we're going to maintain 0.7.x version until the adoption of 0.8.x will be completed
  pull_request:
    branches:
      - main
      - 0.7.x # we're going to maintain 0.7.x version until the adoption of 0.8.x will be completed

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run check
      run: cargo check

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run check
      run: cargo test

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: rustfmt
    - name: Check formatting
      run: |
        cargo fmt -- --check

  rustclippy:
    name: rustclippy
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: clippy
    - name: Clippy check
      run: |
        cargo clippy

  release-plz:
    name: release-plz
    runs-on: ubuntu-latest
    needs: [check, rustclippy, rustfmt, test]
    if: ${{ github.event_name != 'pull_request' }}  # Specify the branch condition
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          # https://marcoieni.github.io/release-plz/github/trigger.html
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
